services:
  postgres:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  pgdata: